server:
  port: 8088


  #????
  logging:
    level:
      com:
        demo: debug


#???
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

#mybatis
mybatis:
  #  Mapper?????? classpath????? resources ???
  mapper-locations: classpath:/mapper/*.xml
  #  ?????????Ming =  m_ing
  map-underscore-to-camel-case: true
  #  ? - ???
  type-aliases-package: com.demo.pojo